import time
import os
import sys
import colorama

def sekilliprint(s):
    for c in s + '\n' :
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(5. / 100)


time.sleep(4)

sekilliprint("Welcome to Install Termux All Packages!")

os.system("clear")

time.sleep(3)

print('''

█████╗  ███╗   ██╗ ██████╗  ██████╗ ██╗  ██╗
██╔══██╗████╗  ██║██╔═══██╗██╔═══██╗╚██╗██╔╝
███████║██╔██╗ ██║██║   ██║██║   ██║ ╚███╔╝ 
██╔══██║██║╚██╗██║██║   ██║██║   ██║ ██╔██╗ 
██║  ██║██║ ╚████║╚██████╔╝╚██████╔╝██╔╝ ██╗
╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝
''')

choice = input("\033[93mDo You Want to Install All Packages [y/n] : ")
if choice == 'n' : sys.exit()
if choice == 'y' : os.system ("apt update -y && apt upgrade -y")
os.system ("termux-setup-storage")
os.system ("apt install python -y")
os.system ("apt install python2 -y")
os.system ("apt install php -y")
os.system ("apt install python-dev -y")
os.system ("apt install python3 -y")
os.system ("apt install java -y")
os.system ("apt install git -y")
os.system ("apt install perl -y")
os.system ("apt install bash")
os.system ("apt install nano -y")
os.system ("apt install curl -y")
os.system ("apt install openssl -y")
os.system ("apt install openssh -y")
os.system ("apt install wget -y")
os.system ("apt install clang -y")
os.system ("apt install nmap -y")
os.system ("apt install w3m -y")
os.system ("apt install hydra -y")
os.system ("apt install ruby -y")
os.system ("apt install macchanger -y")
os.system ("apt install host -y")
os.system ("apt install dnsutils -y")
os.system ("apt install coreutils -y")
os.system ("apt install fish -y")
os.system ("apt install zip -y")
os.system ("apt install hydra -y")
os.system ("apt install figlet -y")
os.system ("apt install cowsay -y")
os.system ("apt install unzip -y")
os.system ("apt install vim -y")
os.system ("apt install ruby -y")
os.system ("apt install wcalc -y")
os.system ("apt install bmon -y")
os.system ("apt install unrar -y")
os.system ("apt install proot -y")
os.system ("apt install golang -y")
os.system ("apt install toilet -y")
os.system ("pip install stdiomask")
os.system ("pip install requests")
os.system ("pip install bs4")
os.system ("pip install colorama")
os.system ("pip install mechanize")
os.system ("pip install lolcat")
os.system ("pip install gem")
os.system ("pip install pytube")
os.system ("pip install rich")
os.system ("pip install pycryptodome")
os.system ("pip install datetime")
os.system ("pip install proxybroker")
os.system ("pip install colorama")
os.system ("apt install ncurses-utils")
os.system ("apt install apache2 -y")
os.system ("pkg install curl -y")
os.system ("pkg install php -y")
os.system ("pkg install libcaca -y")
os.system ("apt install cmatrix -y")
os.system ("pip install requests")
os.system ("pkg install libxml2-utils -y")
os.system ("pkg install jq -y")
os.system ("pkg install bc -y")
os.system ("pkg install htop -y")
os.system ("pkg install httping -y")
os.system ("pkg install ffmpeg -y")
os.system ("pkg install clang -y")
os.system ("pip install ddgr -y")
os.system ("pkg install rust -y")
os.system ("pkg install Cloudflared -y")
os.system ("pkg install sqlite -y")
os.system ("pkg install neofetch -y")
os.system ("pkg install sqlite -y")
os.system ("pkg install fakeroot -y")
os.system ("pkg install sshpass -y")
os.system ("pkg install golang -y")
os.system ("pkg install termux-exec -y")
os.system ("pkg install termux-api -y")
os.system ("pkg install tur-repo -y")
os.system ("pkg install code-server -y")
os.system ("apt install tor -y")
os.system ("pkg install bzip2 -y")
os.system ("pkg install coreutils -y")
os.system ("pkg install zsh -y")
os.system ("pkg install zlib -y")
os.system ("pkg install xz-utils -y")
os.system ("pkg install xxhash -y")
os.system ("pkg install unbound -y")
os.system ("pkg install tsu -y")
os.system ("pkg install tar -y")
os.system ("pkg install termux-tools -y")
os.system ("pkg install termux-licenses -y")
os.system ("pkg install termux-keyring")
os.system ("pkg install termux-exec -y")
os.system ("pkg install termux-auth -y")
os.system ("pkg install termux-am -y")
os.system ("pkg install termux-am-socket -y")
os.system ("pkg install psmisc -y")
os.system ("pkg install procps -y")
os.system ("pkg install patch -y")
os.system ("pkg install pando -y")
os.system ("pip install ninja")
os.system ("pkg install net-tools -y")
os.system ("pkg install ncurses -y")
os.system ("pkg install ncurses-utils -y")
os.system ("pkg install lynex -y")
os.system ("pkg install libunistring -y")
os.system ("pkg install pcre -y")
os.system ("pkg install pcre2 -y")
os.system ("pkg install libtirpc -y")
os.system ("pkg install libssh2 -y")
os.system ("pkg install libnpth -y")
os.system ("pkg install libnghttp2 -y")
os.system ("pkg install libmpfr -y")
os.system ("wget -O install-nethunter-termux https://offs.ec/2MceZWr")
os.system ("git clone https://github.com/RiSecID/parrot-in-termux.git")
os.system ("pkg install gawk -y")
os.system ("pkg install less -y")
os.system("pkg list-installed")
os.system ("ls")